name: check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # cada 30 minutos

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validate secrets
        run: |
          if [ -z "${API_BASE}" ] || [ -z "${API_TOKEN}" ]; then
            echo "Missing required secrets: API_BASE or API_TOKEN"
            exit 1
          fi
          echo "Secrets validation passed."
        env:
          API_BASE: ${{ secrets.API_BASE }}
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Install deps
        run: npm install

      # ⬇️ Paso clave de la Opción A: instala el módulo 'playwright'
      - name: Install Playwright (module)
        run: npm install --no-save playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          API_BASE: ${{ secrets.API_BASE }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: node scripts/uscis_check.cjs
