name: USCIS Case Checker

on:
  workflow_dispatch:
  schedule:
    # Corre cada hora (ajusta si quieres)
    - cron: "0 * * * *"

concurrency:
  group: uscis-checker
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Print environment details
        run: |
          echo "node: $(node -v)"
          echo "npm:  $(npm -v)"

      - name: Install npm deps
        run: npm install

      # Si playright ya está en package.json, esta línea bastaría.
      # La dejo adicional para garantizar que siempre esté.
      - name: Ensure Playwright package
        run: npm install --no-save playwright

      - name: Install Playwright (Chromium + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          API_BASE: ${{ secrets.API_BASE }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          # Opcional: limita items por corrida (default 10)
          LIMIT: "10"
          # Opcional: forzar cola (si backend lo soporta). "1" = on, "" = off
          FORCE: ""
        run: node scripts/uscis_check.cjs
