name: USCIS Check (self-hosted)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # cada 30 minutos

jobs:
  run-check:
    runs-on: self-hosted
    timeout-minutes: 20

    env:
      # Playwright/Navegador
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      BROWSER: 'chrome-channel'
      HEADFUL: '1'
      NODE_ENV: 'production'

      # Proxy (opcional)
      PROXY_ENABLED: ${{ secrets.PROXY_ENABLED }}
      PROXY_HOST:    ${{ secrets.PROXY_HOST }}
      PROXY_PORT:    ${{ secrets.PROXY_PORT }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}

      # API
      API_BASE:  ${{ secrets.API_BASE }}   # por ej: https://aroeservices.com/api
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Show Chrome version (del sistema)
        run: |
          which google-chrome || which google-chrome-stable || true
          google-chrome --version || google-chrome-stable --version || true

      - name: Run checker (Xvfb) con reintentos
        env:
          NAV_TIMEOUT_MS: '90000'   # 90s p/ redes lentas
        run: |
          set -e
          for i in 1 2 3; do
            echo ">>> Intento $i"
            xvfb-run -s "-screen 0 1366x768x24" -a node scripts/uscis_check.cjs && break || {
              code=$?
              echo "Intento $i falló (exit $code); esperando $((i*20))s…"
              sleep $((i*20))
              if [ $i -eq 3 ]; then exit $code; fi
            }
          done

      - name: Upload logs & report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-and-report
          path: |
            logs/**
            *.log
            playwright-report/**
          if-no-files-found: ignore
