name: USCIS Check (self-hosted)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # cada 30 minutos

jobs:
  run-check:
    runs-on: self-hosted
    timeout-minutes: 25

    env:
      # Playwright/Chrome (usamos Chrome del sistema del runner)
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      BROWSER: 'chrome-channel'
      HEADFUL: '1'
      NODE_ENV: 'production'

      # Proxy (opcional, deja vacío si no usas)
      PROXY_ENABLED: ${{ secrets.PROXY_ENABLED }}
      PROXY_HOST:    ${{ secrets.PROXY_HOST }}
      PROXY_PORT:    ${{ secrets.PROXY_PORT }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}

      # API
      API_BASE:  ${{ secrets.API_BASE }}    # p.ej. https://aroeservices.com/api
      API_TOKEN: ${{ secrets.API_TOKEN }}
      # Estas 2 son opcionales: si no las defines, el script usa /queue y /result
      API_QUEUE_PATH:  ${{ secrets.API_QUEUE_PATH }}
      API_RESULT_PATH: ${{ secrets.API_RESULT_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Show Chrome version (del sistema)
        run: |
          which google-chrome || which google-chrome-stable || true
          google-chrome --version || google-chrome-stable --version || true

      - name: Run checker (Xvfb)
        run: |
          set -e
          xvfb-run -s "-screen 0 1366x768x24" -a node scripts/uscis_check.cjs

      - name: Upload logs & report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-and-report
          path: |
            logs/**
            *.log
            playwright-report/**
            screenshots/**
            pages/**
          if-no-files-found: ignore
