name: USCIS Case Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # cada hora

concurrency:
  group: uscis-checker
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm   # <- REMOVIDO: requiere lockfile y aquí no lo tenemos

      - name: Install dependencies
        run: npm install

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium

      - name: Run scraper (headed via Xvfb)
        env:
          API_BASE: ${{ secrets.API_BASE }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          HEADFUL: "1"   # navegador visible (mejora el pase de Cloudflare)
          DEBUG: "0"
          # LIMIT: "10"
        run: xvfb-run -a npm run check
