name: USCIS Check (Self-hosted) - debug

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: self-hosted   # ← simplificado para probar emparejamiento
    steps:
      - name: Who am I?
        run: |
          uname -a
          echo "Runner labels: $RUNNER_OS $RUNNER_ARCH (self-hosted)"
          echo "Home: $HOME  User: $(whoami)"
      - name: Node/Chrome versions
        run: |
          node -v || true
          npm -v || true
          google-chrome --version || true
