name: USCIS Case Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # cada hora (ajústalo si quieres)

concurrency:
  group: uscis-checker
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium

      # Ejecutar en modo HEADFUL bajo Xvfb para ayudar a pasar Cloudflare
      - name: Run scraper (headed via Xvfb)
        env:
          API_BASE: ${{ secrets.API_BASE }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          HEADFUL: "1"     # <- clave para que el script levante el browser "visible"
          DEBUG: "0"
          # Opcionales:
          # LIMIT: "10"
        run: xvfb-run -a npm run check
